In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
data = pd.read_csv('/content/purchase_data.csv')

In [4]:
data

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
0,1000001,P00069042,F,0-17,10,A,2,0,3,NaN,NaN,8370
1,1000001,P00248942,F,0-17,10,A,2,0,1,6.0,14.0,15200
2,1000001,P00087842,F,0-17,10,A,2,0,12,NaN,NaN,1422
3,1000001,P00085442,F,0-17,10,A,2,0,12,14.0,NaN,1057
4,1000002,P00285442,M,55+,16,C,4+,0,8,NaN,NaN,7969
...,...,...,...,...,...,...,...,...,...,...,...,...
550063,1006033,P00372445,M,51-55,13,B,1,1,20,NaN,NaN,368
550064,1006035,P00375436,F,26-35,1,C,3,0,20,NaN,NaN,371
550065,1006036,P00375436,F,26-35,15,B,4+,1,20,NaN,NaN,137
550066,1006038,P00375436,F,55+,1,C,2,0,20,NaN,NaN,365
550067,1006039,P00371644,F,46-50,0,B,4+,1,20,NaN,NaN,490

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 550068 entries, 0 to 550067
Data columns (total 12 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   User_ID                     550068 non-null  int64
 1   Product_ID                  550068 non-null  object
 2   Gender                      550068 non-null  object
 3   Age                         550068 non-null  object
 4   Occupation                  550068 non-null  int64
 5   City_Category               550068 non-null  object
 6   Stay_In_Current_City_Years  550068 non-null  object
 7   Marital_Status              550068 non-null  int64
 8   Product_Category_1          550068 non-null  int64
 9   Product_Category_2          376430 non-null  float64
 10  Product_Category_3          166821 non-null  float64
 11  Purchase                    550068 non-null  int64
dtypes: float64(2), int64(5), object(5)
memory usage: 50.4+ MB

In [6]:
data.isnull().sum()

User_ID                            0
Product_ID                         0
Gender                             0
Age                                0
Occupation                         0
City_Category                      0
Stay_In_Current_City_Years         0
Marital_Status                     0
Product_Category_1                 0
Product_Category_2            173638
Product_Category_3            383247
Purchase                           0
dtype: int64

In [7]:
data.duplicated().sum()

np.int64(0)

In [8]:
data.dropna(inplace=True)

In [9]:
data.isnull().sum()

User_ID                       0
Product_ID                    0
Gender                        0
Age                           0
Occupation                    0
City_Category                 0
Stay_In_Current_City_Years    0
Marital_Status                0
Product_Category_1            0
Product_Category_2            0
Product_Category_3            0
Purchase                      0
dtype: int64

#Label Encoding

In [10]:
data.columns

Index(['User_ID', 'Product_ID', 'Gender', 'Age', 'Occupation', 'City_Category',
       'Stay_In_Current_City_Years', 'Marital_Status', 'Product_Category_1',
       'Product_Category_2', 'Product_Category_3', 'Purchase'],
      dtype='object')

In [11]:
data['Gender'].nunique()

2

In [12]:
data['Gender'].unique()

array(['F', 'M'], dtype=object)

In [13]:
data['Gender'].value_counts()

Gender
M    129227
F     37594
Name: count, dtype: int64

In [14]:
data.dtypes

User_ID                         int64
Product_ID                     object
Gender                         object
Age                            object
Occupation                      int64
City_Category                  object
Stay_In_Current_City_Years     object
Marital_Status                  int64
Product_Category_1              int64
Product_Category_2            float64
Product_Category_3            float64
Purchase                        int64
dtype: object

In [15]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [16]:
data['Product_ID'] = le.fit_transform(data['Product_ID'])
data['Gender'] = le.fit_transform(data['Gender'])
data['Age'] = le.fit_transform(data['Age'])
data['City_Category'] = le.fit_transform(data['City_Category'])
data['Stay_In_Current_City_Years'] = le.fit_transform(data['Stay_In_Current_City_Years'])

In [17]:
#Data['Gender'].unique()
#array(['F','M'], dtype = object)

data['Gender'].unique()

array([0, 1])

In [18]:
data['Age'].unique()
# array(['0-17','46-50','26-35','51-55','36-45','18-25','55+'], dtype = object)
# array([  0,      4 ,      2,      5,      3,     1   ,   6 ])

array([0, 4, 2, 5, 3, 1, 6])

#It was observed that the average purchase made by the men of the age 18-25 was 10000. Is it still the same?

In [ ]:
# write down null and alternate hypothesis.
# create a sub data based on condition
# we need to create a sample
# we perform hypothesis testing
# we conclude if it is null or alternate hypothesis

In [ ]:
# null - average purchase made by men of the age 18-25 age is 10000.
# alternate - average purchase made by men of the age 18-25 is not 100000.

In [19]:
new_data = data.loc[(data['Age']==1)&(data['Gender']==1)]

In [20]:
new_data

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
98,1000022,490,1,1,15,0,4,0,1,8.0,17.0,12099
103,1000022,405,1,1,15,0,4,0,1,11.0,16.0,12098
111,1000022,361,1,1,15,0,4,0,2,4.0,15.0,9564
127,1000025,335,1,1,4,2,4,0,1,5.0,9.0,15361
128,1000025,72,1,1,4,2,4,0,1,2.0,15.0,15770
...,...,...,...,...,...,...,...,...,...,...,...,...
545425,1005964,52,1,1,5,1,1,0,1,14.0,16.0,15420
545427,1005964,314,1,1,5,1,1,0,2,3.0,4.0,15973
545428,1005964,249,1,1,5,1,1,0,2,15.0,16.0,6847
545430,1005964,253,1,1,5,1,1,0,2,4.0,5.0,13276
545438,1005964,228,1,1,5,1,1,0,11,13.0,16.0,3125

In [21]:
sample_size=1000

In [22]:
data.sample(5, random_state=0)

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
53490,1002129,78,1,2,5,1,1,0,5,6.0,11.0,6914
115274,1005788,475,1,2,0,0,4,0,11,15.0,16.0,1653
456169,1004213,142,1,3,7,1,4,0,1,2.0,15.0,15823
78393,1000045,177,0,4,16,0,1,1,1,5.0,18.0,11675
232777,1005888,276,1,2,20,1,1,0,1,5.0,6.0,15504

In [23]:
sample=new_data.sample(1000,random_state=4)

In [24]:
sample

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
256923,1003621,293,1,1,4,1,3,0,2,4.0,15.0,6744
157272,1000295,119,1,1,0,2,4,0,1,6.0,8.0,15207
249520,1002446,187,1,1,7,1,0,0,1,2.0,5.0,11985
119337,1000419,173,1,1,3,2,1,0,3,4.0,12.0,13247
258107,1003777,179,1,1,4,1,0,0,1,2.0,15.0,11724
...,...,...,...,...,...,...,...,...,...,...,...,...
281994,1001447,160,1,1,4,0,0,0,1,8.0,17.0,15238
478263,1001655,94,1,1,4,2,2,1,6,8.0,16.0,16649
128899,1001828,442,1,1,4,1,1,0,5,8.0,14.0,7134
472247,1000777,386,1,1,19,1,1,0,1,2.0,15.0,11856
174979,1003077,79,1,1,4,1,2,0,5,14.0,16.0,7048

In [25]:
# one sample t test

from scipy.stats import ttest_1samp

In [26]:
t_test,p_value=ttest_1samp(sample['Purchase'],10000)

In [27]:
p_value

np.float64(5.216833228904613e-31)

In [28]:
if p_value<0.05:
  print('alternate - average purchase made by men of the age 18-25 is not 10000')
else:
  print('null - average purchase made by men of the age 18-25 is not 10000.')

alternate - average purchase made by men of the age 18-25 is not 10000

#Is the average purchase made by men and women of the age 18-25 same?

In [ ]:
# write down null and alternate hypothesis.
# create a sub data based on condition
# we need to create sample
# we perform hypothesis testing
# we conclude if it is null or alternate hypothesis

In [ ]:
# null - average purchase made by men and women of the age 18-25 same
# alternate - average purchase made by men and women of the age 18-25 are not same

In [29]:
data_men = data.loc[(data['Age']==1)&(data['Gender']==1)]
data_women = data.loc[(data['Age']==0)&(data['Gender']==1)]

In [30]:
data_women

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
85,1000019,154,1,0,10,0,3,0,1,11.0,15.0,7746
87,1000019,186,1,0,10,0,3,0,1,2.0,15.0,11959
88,1000019,179,1,0,10,0,3,0,1,2.0,15.0,19172
93,1000019,92,1,0,10,0,3,0,3,4.0,12.0,8290
95,1000019,398,1,0,10,0,3,0,1,2.0,4.0,4211
...,...,...,...,...,...,...,...,...,...,...,...,...
543994,1005757,126,1,0,10,2,2,0,2,4.0,8.0,16040
543996,1005757,192,1,0,10,2,2,0,1,5.0,15.0,11434
544386,1005803,431,1,0,10,2,1,0,3,4.0,5.0,2639
545311,1005953,345,1,0,10,1,0,0,3,4.0,5.0,13370
545465,1005973,437,1,0,10,2,4,0,2,5.0,15.0,16132

In [31]:
data_men

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
98,1000022,490,1,1,15,0,4,0,1,8.0,17.0,12099
103,1000022,405,1,1,15,0,4,0,1,11.0,16.0,12098
111,1000022,361,1,1,15,0,4,0,2,4.0,15.0,9564
127,1000025,335,1,1,4,2,4,0,1,5.0,9.0,15361
128,1000025,72,1,1,4,2,4,0,1,2.0,15.0,15770
...,...,...,...,...,...,...,...,...,...,...,...,...
545425,1005964,52,1,1,5,1,1,0,1,14.0,16.0,15420
545427,1005964,314,1,1,5,1,1,0,2,3.0,4.0,15973
545428,1005964,249,1,1,5,1,1,0,2,15.0,16.0,6847
545430,1005964,253,1,1,5,1,1,0,2,4.0,5.0,13276
545438,1005964,228,1,1,5,1,1,0,11,13.0,16.0,3125

In [33]:
data_men.shape

(24239, 12)

In [34]:
data_women.shape

(3301, 12)

In [35]:
sample_size = 1000

In [36]:
data_men_sample=data_men.sample(sample_size,random_state=0)
data_women_sample=data_women.sample(sample_size,random_state=0)

In [37]:
data_men_sample

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
529454,1003579,184,1,1,0,2,2,0,1,2.0,15.0,11599
6939,1001112,242,1,1,6,0,4,0,5,6.0,13.0,5387
249217,1002379,303,1,1,18,2,1,0,3,4.0,9.0,10833
118440,1000271,300,1,1,4,2,1,0,3,4.0,5.0,10649
93327,1002350,501,1,1,4,2,1,1,11,15.0,16.0,3163
...,...,...,...,...,...,...,...,...,...,...,...,...
334055,1003484,72,1,1,4,2,1,0,1,2.0,15.0,15659
156781,1000202,87,1,1,4,0,3,0,3,4.0,5.0,8284
121262,1000747,214,1,1,4,2,4,1,1,2.0,5.0,8263
490848,1003622,120,1,1,1,1,2,1,6,8.0,14.0,16222
322208,1001628,431,1,1,20,1,1,0,3,4.0,5.0,13444

In [38]:
data_women_sample

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
90511,1001919,13,1,0,0,2,1,0,1,5.0,6.0,15817
7443,1001163,99,1,0,10,2,2,0,1,2.0,13.0,7752
139600,1003573,48,1,0,10,1,1,0,1,2.0,15.0,19058
259746,1004006,419,1,0,7,2,3,0,1,6.0,15.0,15402
185213,1004541,110,1,0,10,1,1,0,1,15.0,17.0,19280
...,...,...,...,...,...,...,...,...,...,...,...,...
405171,1002288,214,1,0,10,1,2,0,1,2.0,5.0,8270
108141,1004633,93,1,0,0,1,1,0,3,4.0,12.0,3090
436389,1001182,135,1,0,10,1,3,0,1,2.0,14.0,11733
209275,1002195,345,1,0,10,0,0,0,3,4.0,5.0,2901
124340,1001198,367,1,0,10,2,1,0,1,11.0,15.0,12016

In [40]:
print(data_men_sample['Purchase'].var())
print(data_women_sample['Purchase'].var())

25944736.709620655
28081037.55345345

In [41]:
from scipy.stats import ttest_ind
t_stats,p_val=ttest_ind(data_men_sample['Purchase'],data_women_sample['Purchase'],equal_var=True)

In [42]:
p_val

np.float64(0.16019387861434942)

In [43]:
if p_value<0.05:
  print('Alternate')
else:
  print('Null')

Alternate

#Mean of Product_category_1,Product_category_1,Product_category_1 are same

In [45]:
from scipy.stats import f_oneway

In [50]:
samp1 = data['Product_Category_1']
samp2 = data['Product_Category_2']
samp3 = data['Product_Category_3']

In [51]:
a_stat,p_value=f_oneway(samp1,samp2,samp3)

In [52]:
p_value

np.float64(0.0)